services:
  db:
    container_name: db-container
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=tci_db'
      - 'POSTGRES_PASSWORD=030809'
      - 'POSTGRES_USER=med'
    ports:
      - '5432:5432'
    volumes:
      - db-pg-data:/var/lib/postgresql/data

volumes:
  db-pg-data: